spring.datasource.url=jdbc:mysql://localhost:3306/traveldb
spring.datasource.username=root
spring.datasource.password=sairamya2005#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8000